// 渲染：给人看的文本战报 + 可以发出去的 SVG 卡片。
//
// 脱敏原则（默认开）：
//   - 项目名只保留最后一段（Users/xxx/project/dsh-plugin → dsh-plugin），不暴露用户名；
//   - 文件只出现 basename 和计数，不出现绝对路径、不出现任何对话内容；
//   - 会话 id 只显示前 8 位。
// 想给同事看完整路径时才用 --show-paths。

const FONT = "-apple-system, BlinkMacSystemFont, 'PingFang SC', 'Helvetica Neue', Arial, sans-serif";

export function shortId(id) {
  return typeof id === 'string' && id.length > 8 ? id.slice(0, 8) : (id ?? '—');
}

/** 项目名脱敏：只留最后一段目录名。 */
export function redactProject(project) {
  if (typeof project !== 'string' || project === '') return '—';
  const parts = project.split('/').filter((part) => part !== '');
  return parts[parts.length - 1] ?? '—';
}

export function formatDuration(minutes) {
  if (minutes < 1) return '<1 分钟';
  if (minutes < 60) return `${minutes} 分钟`;
  const hours = Math.floor(minutes / 60);
  const rest = minutes % 60;
  return rest === 0 ? `${hours} 小时` : `${hours} 小时 ${rest} 分`;
}

export function formatNumber(value) {
  return Number(value ?? 0).toLocaleString('en-US');
}

/** 大数字压缩：1,774,678 → 1.77M，中文语境用万。 */
export function compactNumber(value, lang = 'zh') {
  const n = Number(value ?? 0);
  if (lang === 'zh') {
    if (n >= 100_000_000) return `${(n / 100_000_000).toFixed(2)} 亿`;
    if (n >= 10_000) return `${(n / 10_000).toFixed(1)} 万`;
    return formatNumber(n);
  }
  if (n >= 1_000_000) return `${(n / 1_000_000).toFixed(2)}M`;
  if (n >= 1_000) return `${(n / 1_000).toFixed(1)}K`;
  return formatNumber(n);
}

const LABELS = {
  zh: {
    title: '会话战报',
    periodTitle: '周期战报',
    sessions: '会话数', projects: '项目数', span: '时间跨度', sessionTotal: '会话时长合计（含挂机，会重复计算）',
    session: '会话', project: '项目', model: '模型', duration: '时长',
    turns: '轮次', steps: '步数', messages: '消息', userMsgs: '我的输入',
    toolCalls: '工具调用', files: '涉及文件', tokens: 'tokens', input: '输入（新）',
    output: '输出', cacheRead: '缓存读', compaction: '上下文压缩', pruned: '被裁掉',
    topTools: '用得最多的工具', footer: '由 dsh-receipt 生成 · 数字取自会话日志 · 默认脱敏',
    noCost: '未给单价，不估成本', cost: '估算成本', times: '次',
  },
  en: {
    title: 'SESSION RECEIPT',
    periodTitle: 'PERIOD RECEIPT',
    sessions: 'sessions', projects: 'projects', span: 'time span', sessionTotal: 'session time (sum, counts idle + overlaps)',
    session: 'session', project: 'project', model: 'model', duration: 'duration',
    turns: 'turns', steps: 'steps', messages: 'messages', userMsgs: 'my prompts',
    toolCalls: 'tool calls', files: 'files touched', tokens: 'tokens', input: 'input (fresh)',
    output: 'output', cacheRead: 'cache read', compaction: 'compactions', pruned: 'pruned',
    topTools: 'most used tools', footer: 'generated by dsh-receipt · numbers from the session log · redacted by default',
    noCost: 'no unit price given', cost: 'estimated cost', times: '',
  },
};

/** 文本战报。 */
export function renderText(stats, { lang = 'zh', cost = null, showPaths = false, title = null } = {}) {
  const label = LABELS[lang] ?? LABELS.zh;
  const lines = [];
  const isAggregate = Number(stats.sessionCount ?? 0) > 1;
  lines.push(`${title ?? (isAggregate ? label.periodTitle : label.title)}${isAggregate ? '' : `   ${shortId(stats.sessionId)}`}`);
  if (isAggregate) {
    lines.push(`  ${label.sessions}  ${stats.sessionCount}    ${label.projects}  ${stats.projectCount}`.replace('会话数', '会话数'));
    void 0;
    lines.push(`  ${label.span}      ${formatDuration(stats.spanMinutes)}（${stats.firstAt?.slice(0, 10)} → ${stats.lastAt?.slice(0, 10)}）`);
    lines.push(`  ${label.sessionTotal}  ${formatDuration(stats.durationMinutes)}`);
  }
  if (!isAggregate) lines.push(`  ${label.project}   ${showPaths ? (stats.project ?? '—') : redactProject(stats.project)}`);
  if (stats.models.length > 0) lines.push(`  ${label.model}     ${stats.models.join(', ')}`);
  if (!isAggregate) lines.push(`  ${label.duration}  ${formatDuration(stats.durationMinutes)}${stats.firstAt ? `（${stats.firstAt.slice(0, 16).replace('T', ' ')} 起）` : ''}`);
  lines.push('');
  lines.push(`  ${label.turns}      ${stats.turns}`);
  lines.push(`  ${label.steps}      ${stats.steps}`);
  lines.push(`  ${label.toolCalls}  ${formatNumber(stats.toolCalls)}`);
  lines.push(`  ${label.files}      ${stats.filesTouched}`);
  lines.push(`  ${label.messages}    ${formatNumber(stats.assistantMessages)}（${label.userMsgs} ${stats.userMessages}）`);
  lines.push('');
  lines.push(`  ${label.tokens}`);
  lines.push(`    ${label.input}     ${formatNumber(stats.tokens.input)}`);
  lines.push(`    ${label.output}    ${formatNumber(stats.tokens.output)}`);
  lines.push(`    ${label.cacheRead} ${formatNumber(stats.tokens.cacheRead)}`);
  lines.push('');
  lines.push(`  ${label.compaction}  ${stats.compactions} ${label.times}（${label.pruned} ${formatNumber(stats.prunedTokens)} tokens）`);
  lines.push('');
  if (stats.tools.length > 0) {
    lines.push(`  ${label.topTools}：`);
    for (const tool of stats.tools.slice(0, 8)) lines.push(`    ${String(tool.count).padStart(5)}  ${tool.name}`);
  }
  if (stats.filesTouched > 0) {
    lines.push('');
    lines.push(`  ${label.files}：${stats.files.slice(0, 10).join('、')}${stats.filesTouched > 10 ? ` …等 ${stats.filesTouched} 个` : ''}`);
  }
  lines.push('');
  lines.push(cost === null ? `  ${label.cost}：${label.noCost}` : `  ${label.cost}：$${cost.total.toFixed(4)}`);
  return lines.join('\n');
}

function escapeXml(text) {
  return String(text)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

/**
 * 可发布的卡片（SVG，1080×1350，适合直接发 X）。
 * 不用 canvas/图片依赖：纯文本 SVG，任何浏览器都能渲染，也能再转 PNG。
 */
export function renderSvg(stats, { lang = 'zh', cost = null, theme = 'dark', title = null } = {}) {
  const label = LABELS[lang] ?? LABELS.zh;
  const isAggregate = Number(stats.sessionCount ?? 0) > 1;
  const width = 1080;
  const height = 1350;
  const pad = 84;
  const palette = theme === 'light'
    ? { bg: '#f7f7f5', card: '#ffffff', text: '#111111', dim: '#6b6b6b', line: '#e3e3e0', accent: '#c2410c' }
    : { bg: '#0b0e14', card: '#12161f', text: '#f2f4f8', dim: '#8b93a7', line: '#232a38', accent: '#ff7a45' };

  // 布局用「预算」而不是硬编码：先留出页脚，再按剩余高度决定能画几行，
  // 否则行数一多就会压到页脚上（第一版就是这样，工具列表和页脚叠在了一起）。
  const footerY = height - pad / 2 - 52;
  const bottomLimit = footerY - 46;

  const summaryRows = (isAggregate ? [[label.sessionTotal, formatDuration(stats.durationMinutes)]] : []).concat([
    [label.turns, formatNumber(stats.turns)],
    [label.steps, formatNumber(stats.steps)],
    [label.toolCalls, formatNumber(stats.toolCalls)],
    [label.files, formatNumber(stats.filesTouched)],
    [label.messages, `${formatNumber(stats.assistantMessages)} / ${stats.userMessages}`],
  ]);
  const tokenRows = [
    [label.input, formatNumber(stats.tokens.input)],
    [label.output, formatNumber(stats.tokens.output)],
    [label.cacheRead, formatNumber(stats.tokens.cacheRead)],
  ];
  const topTools = stats.tools.slice(0, 6);

  const parts = [];
  parts.push(`<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}">`);
  parts.push(`<rect width="${width}" height="${height}" fill="${palette.bg}"/>`);
  parts.push(`<rect x="${pad / 2}" y="${pad / 2}" width="${width - pad}" height="${height - pad}" rx="28" fill="${palette.card}" stroke="${palette.line}"/>`);

  const row = (name, value, { size = 30, gap = 62, offset = 0, valueSize = 34 } = {}) => {
    if (y + offset > bottomLimit) return false;
    parts.push(`<text x="${pad + offset}" y="${y}" font-family="${FONT}" font-size="${size}" fill="${palette.dim}">${escapeXml(name)}</text>`);
    parts.push(`<text x="${width - pad}" y="${y}" font-family="${FONT}" font-size="${valueSize}" font-weight="600" text-anchor="end" fill="${palette.text}">${escapeXml(value)}</text>`);
    y += gap;
    return true;
  };
  const sectionTitle = (text) => {
    if (y + 20 > bottomLimit) return false;
    parts.push(`<text x="${pad}" y="${y}" font-family="${FONT}" font-size="26" letter-spacing="3" fill="${palette.dim}">${escapeXml(text)}</text>`);
    y += 46;
    return true;
  };
  const divider = () => {
    if (y + 10 > bottomLimit) return false;
    parts.push(`<line x1="${pad}" y1="${y}" x2="${width - pad}" y2="${y}" stroke="${palette.line}" stroke-width="2"/>`);
    y += 46;
    return true;
  };

  let y = pad + 26;
  // 头部：标题 + 大数字（时长）
  parts.push(`<text x="${pad}" y="${y}" font-family="${FONT}" font-size="28" letter-spacing="8" fill="${palette.accent}">${escapeXml(title ?? (isAggregate ? label.periodTitle : label.title))}</text>`);
  y += 76;
  parts.push(`<text x="${pad}" y="${y}" font-family="${FONT}" font-size="70" font-weight="700" fill="${palette.text}">${escapeXml(formatDuration(stats.durationMinutes))}</text>`);
  y += 48;
  const sub = (isAggregate
    ? [
        lang === 'zh' ? `${stats.sessionCount} 个会话` : `${stats.sessionCount} sessions`,
        lang === 'zh' ? `${stats.projectCount} 个项目` : `${stats.projectCount} projects`,
        stats.firstAt !== null ? `${stats.firstAt.slice(0, 10)} → ${stats.lastAt.slice(0, 10)}` : null,
      ]
    : [
        `${label.project}: ${redactProject(stats.project)}`,
        `${label.session}: ${shortId(stats.sessionId)}`,
      ]).concat(stats.models.length > 0 ? [`${label.model}: ${stats.models[0]}`] : []).filter(Boolean).join('   ·   ');
  parts.push(`<text x="${pad}" y="${y}" font-family="${FONT}" font-size="26" fill="${palette.dim}">${escapeXml(sub)}</text>`);
  y += 40;
  divider();

  for (const [name, value] of summaryRows) row(name, value);
  divider();
  if (sectionTitle(label.tokens.toUpperCase())) {
    for (const [name, value] of tokenRows) row(name, value, { size: 27, valueSize: 29, gap: 46, offset: 22 });
  }
  if (topTools.length > 0 && divider() && sectionTitle(label.topTools.toUpperCase())) {
    for (const tool of topTools) {
      if (!row(tool.name, formatNumber(tool.count), { size: 27, valueSize: 27, gap: 42, offset: 22 })) break;
    }
  }
  if (stats.compactions > 0 && y + 30 <= bottomLimit) {
    parts.push(`<text x="${pad}" y="${y}" font-family="${FONT}" font-size="24" fill="${palette.dim}">${escapeXml(`${label.compaction}: ${stats.compactions}    ${label.pruned}: ${formatNumber(stats.prunedTokens)} tokens`)}</text>`);
  }

  if (cost !== null) {
    parts.push(`<text x="${pad}" y="${footerY}" font-family="${FONT}" font-size="30" fill="${palette.accent}">${escapeXml(`${label.cost}: $${cost.total.toFixed(4)}`)}</text>`);
  }
  parts.push(`<text x="${pad}" y="${footerY + 40}" font-family="${FONT}" font-size="22" fill="${palette.dim}">${escapeXml(label.footer)}</text>`);
  parts.push('</svg>');
  return parts.join('\n');
}
